# Utilisation d'une image ROS noetic de base
FROM ros_dev:latest

# Éviter le shell interactif pendant l'installation.
ENV DEBIAN_FRONTEND=noninteractive

# Change the default shell to Bash
SHELL [ "/bin/bash" , "-c" ]


#----------------- Ajout des dépendances ---------------

# Installation des dépendances nécessaires pour la raspberry Pi Louise, à compléter si nécessaire
#la 1ère ligne du RUN permet de mettre en cache les packages ainsi si l'on souhaite faire un autre build
#avec les mêmes packages + un autre différents, seulement le nouveau package sera à installer. 
RUN \
    --mount=type=cache,target=/var/cache/apt \
    apt-get update && apt-get install -y \
    python3-pip \
    gedit \
    git \
    vim \
    iputils-ping \
    net-tools \
    && rm -rf /var/lib/apt/lists/* 


# Set dir to requirements_image
WORKDIR /requirements_image
# Copy only the requirements.txt file into the container at /init_image
COPY init/requirements.txt /requirements_image/
# Installation des bibliothèques python nécessaires
RUN python3 -m pip install --no-cache-dir -r requirements.txt


#----------------- Paramétrage du worksapce et des droits admins ---------------

# TODO : Laisser les droits admin à l'hôte sur les fichiers crées dans le conteneur
#Assez casse tête/insecure si mal fait, pour l'instant les droits devront être modifiés directement dans le conteneur avec un chmod

# Ajouter le user root au groupe video
RUN sudo usermod -a -G video root

# Source le workspace à chaque ouverture du terminal
RUN echo "source /Louise_eurobot_2024/_2_ROS/devel/setup.bash" >> ~/.bashrc

# Se déplacer dans le repertoire principal
WORKDIR /Louise_eurobot_2024

#
#-------------------- Fin ---------------------





