# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from balise_msgs/ArrayPositionPx.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import balise_msgs.msg

class ArrayPositionPx(genpy.Message):
  _md5sum = "4d42662441de878808f5bfe3b2bdeae4"
  _type = "balise_msgs/ArrayPositionPx"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """PositionPx[] array_of_positionspx
================================================================================
MSG: balise_msgs/PositionPx
int32 x
int32 y 
int32 theta
"""
  __slots__ = ['array_of_positionspx']
  _slot_types = ['balise_msgs/PositionPx[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       array_of_positionspx

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ArrayPositionPx, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.array_of_positionspx is None:
        self.array_of_positionspx = []
    else:
      self.array_of_positionspx = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.array_of_positionspx)
      buff.write(_struct_I.pack(length))
      for val1 in self.array_of_positionspx:
        _x = val1
        buff.write(_get_struct_3i().pack(_x.x, _x.y, _x.theta))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.array_of_positionspx is None:
        self.array_of_positionspx = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.array_of_positionspx = []
      for i in range(0, length):
        val1 = balise_msgs.msg.PositionPx()
        _x = val1
        start = end
        end += 12
        (_x.x, _x.y, _x.theta,) = _get_struct_3i().unpack(str[start:end])
        self.array_of_positionspx.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.array_of_positionspx)
      buff.write(_struct_I.pack(length))
      for val1 in self.array_of_positionspx:
        _x = val1
        buff.write(_get_struct_3i().pack(_x.x, _x.y, _x.theta))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.array_of_positionspx is None:
        self.array_of_positionspx = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.array_of_positionspx = []
      for i in range(0, length):
        val1 = balise_msgs.msg.PositionPx()
        _x = val1
        start = end
        end += 12
        (_x.x, _x.y, _x.theta,) = _get_struct_3i().unpack(str[start:end])
        self.array_of_positionspx.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3i = None
def _get_struct_3i():
    global _struct_3i
    if _struct_3i is None:
        _struct_3i = struct.Struct("<3i")
    return _struct_3i
