// Generated by gencpp from file balise_msgs/PositionPx.msg
// DO NOT EDIT!


#ifndef BALISE_MSGS_MESSAGE_POSITIONPX_H
#define BALISE_MSGS_MESSAGE_POSITIONPX_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace balise_msgs
{
template <class ContainerAllocator>
struct PositionPx_
{
  typedef PositionPx_<ContainerAllocator> Type;

  PositionPx_()
    : x(0)
    , y(0)
    , theta(0)  {
    }
  PositionPx_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , theta(0)  {
  (void)_alloc;
    }



   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;

   typedef int32_t _theta_type;
  _theta_type theta;





  typedef boost::shared_ptr< ::balise_msgs::PositionPx_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::balise_msgs::PositionPx_<ContainerAllocator> const> ConstPtr;

}; // struct PositionPx_

typedef ::balise_msgs::PositionPx_<std::allocator<void> > PositionPx;

typedef boost::shared_ptr< ::balise_msgs::PositionPx > PositionPxPtr;
typedef boost::shared_ptr< ::balise_msgs::PositionPx const> PositionPxConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::balise_msgs::PositionPx_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::balise_msgs::PositionPx_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::balise_msgs::PositionPx_<ContainerAllocator1> & lhs, const ::balise_msgs::PositionPx_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.theta == rhs.theta;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::balise_msgs::PositionPx_<ContainerAllocator1> & lhs, const ::balise_msgs::PositionPx_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace balise_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::balise_msgs::PositionPx_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::balise_msgs::PositionPx_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::balise_msgs::PositionPx_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::balise_msgs::PositionPx_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::balise_msgs::PositionPx_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::balise_msgs::PositionPx_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::balise_msgs::PositionPx_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2bff1127cd10ca02349c9c72c72be56e";
  }

  static const char* value(const ::balise_msgs::PositionPx_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2bff1127cd10ca02ULL;
  static const uint64_t static_value2 = 0x349c9c72c72be56eULL;
};

template<class ContainerAllocator>
struct DataType< ::balise_msgs::PositionPx_<ContainerAllocator> >
{
  static const char* value()
  {
    return "balise_msgs/PositionPx";
  }

  static const char* value(const ::balise_msgs::PositionPx_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::balise_msgs::PositionPx_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 x\n"
"int32 y \n"
"int32 theta\n"
;
  }

  static const char* value(const ::balise_msgs::PositionPx_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::balise_msgs::PositionPx_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PositionPx_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::balise_msgs::PositionPx_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::balise_msgs::PositionPx_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<int32_t>::stream(s, indent + "  ", v.theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BALISE_MSGS_MESSAGE_POSITIONPX_H
