// Generated by gencpp from file balise_msgs/PositionRobot.msg
// DO NOT EDIT!


#ifndef BALISE_MSGS_MESSAGE_POSITIONROBOT_H
#define BALISE_MSGS_MESSAGE_POSITIONROBOT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace balise_msgs
{
template <class ContainerAllocator>
struct PositionRobot_
{
  typedef PositionRobot_<ContainerAllocator> Type;

  PositionRobot_()
    : x(0)
    , y(0)
    , theta(0)
    , team(0)
    , type()  {
    }
  PositionRobot_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , theta(0)
    , team(0)
    , type(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;

   typedef int32_t _theta_type;
  _theta_type theta;

   typedef int8_t _team_type;
  _team_type team;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _type_type;
  _type_type type;





  typedef boost::shared_ptr< ::balise_msgs::PositionRobot_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::balise_msgs::PositionRobot_<ContainerAllocator> const> ConstPtr;

}; // struct PositionRobot_

typedef ::balise_msgs::PositionRobot_<std::allocator<void> > PositionRobot;

typedef boost::shared_ptr< ::balise_msgs::PositionRobot > PositionRobotPtr;
typedef boost::shared_ptr< ::balise_msgs::PositionRobot const> PositionRobotConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::balise_msgs::PositionRobot_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::balise_msgs::PositionRobot_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::balise_msgs::PositionRobot_<ContainerAllocator1> & lhs, const ::balise_msgs::PositionRobot_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.theta == rhs.theta &&
    lhs.team == rhs.team &&
    lhs.type == rhs.type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::balise_msgs::PositionRobot_<ContainerAllocator1> & lhs, const ::balise_msgs::PositionRobot_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace balise_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::balise_msgs::PositionRobot_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::balise_msgs::PositionRobot_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::balise_msgs::PositionRobot_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::balise_msgs::PositionRobot_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::balise_msgs::PositionRobot_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::balise_msgs::PositionRobot_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::balise_msgs::PositionRobot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb86d22bd0412302c40268f48fe779b4";
  }

  static const char* value(const ::balise_msgs::PositionRobot_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb86d22bd0412302ULL;
  static const uint64_t static_value2 = 0xc40268f48fe779b4ULL;
};

template<class ContainerAllocator>
struct DataType< ::balise_msgs::PositionRobot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "balise_msgs/PositionRobot";
  }

  static const char* value(const ::balise_msgs::PositionRobot_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::balise_msgs::PositionRobot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 x\n"
"int32 y \n"
"int32 theta\n"
"int8 team\n"
"string type\n"
;
  }

  static const char* value(const ::balise_msgs::PositionRobot_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::balise_msgs::PositionRobot_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
      stream.next(m.team);
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PositionRobot_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::balise_msgs::PositionRobot_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::balise_msgs::PositionRobot_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<int32_t>::stream(s, indent + "  ", v.theta);
    s << indent << "team: ";
    Printer<int8_t>::stream(s, indent + "  ", v.team);
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BALISE_MSGS_MESSAGE_POSITIONROBOT_H
